name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build binaries
        run: |
          # Linux x64 (most common)
          bun build index.ts --compile --target=bun-linux-x64 --outfile schema-score-linux-x64
          
          # Linux x64 musl (Alpine, static linking)
          bun build index.ts --compile --target=bun-linux-x64-musl --outfile schema-score-linux-x64-musl
          
          # Linux ARM64
          bun build index.ts --compile --target=bun-linux-arm64 --outfile schema-score-linux-arm64
          
          # macOS Intel
          bun build index.ts --compile --target=bun-darwin-x64 --outfile schema-score-darwin-x64
          
          # macOS Apple Silicon
          bun build index.ts --compile --target=bun-darwin-arm64 --outfile schema-score-darwin-arm64

      - name: Make binaries executable
        run: chmod +x schema-score-*

      - name: Test main binary
        run: |
          echo "type Query { hello: String }" > test-schema.graphql
          ./schema-score-linux-x64-musl test-schema.graphql --silent

      - name: Create checksums
        run: |
          for file in schema-score-*; do
            sha256sum "$file" > "${file}.sha256"
          done

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            schema-score-linux-x64
            schema-score-linux-x64-musl
            schema-score-linux-arm64
            schema-score-darwin-x64
            schema-score-darwin-arm64
            *.sha256
          draft: false
          generate_release_notes: true
          body: |
            ## GraphQL Schema Scorer ${{ github.ref_name }}
            
            ### Available Binaries
            - **schema-score-linux-x64-musl** - Linux x64 (recommended - works everywhere)
            - **schema-score-linux-x64** - Linux x64 (glibc)
            - **schema-score-linux-arm64** - Linux ARM64
            - **schema-score-darwin-x64** - macOS Intel
            - **schema-score-darwin-arm64** - macOS Apple Silicon
            
            ### Quick Start
            ```bash
            # Download
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/schema-score-linux-x64-musl
            chmod +x schema-score-linux-x64-musl
            
            # Run
            ./schema-score-linux-x64-musl schema.graphql
            
            # With reporting
            ./schema-score-linux-x64-musl schema.graphql --report-endpoint https://api.example.com/reports
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}